services:
  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    ports:
      - "5050:5050"
    volumes:
      - ./config:/conf
      - ./config/logs:/usr/src/app/logs
    environment:
      TZ: Europe/Stockholm
    env_file:
      - .env
